module: Only declare set_module_sig_enforced when CONFIG_MODULE_SIG is enabled
Currently, set_module_sig_enforced is declared as long as CONFIG_MODULES
is enabled. This can lead to a linking error when
set_module_sig_enforced is called with CONFIG_MODULE_SIG not enabled,

    ld: security/integrity/ima/ima_appraise.o: in function `ima_appraise_measurement':
    security/integrity/ima/ima_appraise.c:587:(.text+0xbbb): undefined reference to `set_module_sig_enforced'

So only declare set_module_sig_enforced when CONFIG_MODULE_SIG is
enabled.

Note all current callers of set_module_sig_enforced e.g.
security/integrity/ima/ima_efi.c depends on CONFIG_MODULE_SIG enabled.
So this issue hasn't caused a real problem.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202510030029.VRKgik99-lkp@intel.com/